version: '3.1'

services:

  roomix-db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
      POSTGRES_USER: app
    volumes:
      - ./data:/var/lib/postgresql

  roomix-backend: 
    build: 
      context: ./roomix-backend
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://roomix-db:5432/db
    ports:
      - "8080:8080"
    depends_on: 
      - roomix-db

  roomix-frontend: # The name of the service
      image: roomix-frontend-image
      ports:
        - '4200:80' # Port mapping