###
GET http://localhost:8080/room
###
GET http://localhost:8080/room/1
###
GET http://localhost:8080/room/member/1
###
GET http://localhost:8080/room/1/song
###
POST http://localhost:8080/room
Content-Type: application/json

{
  "username": "Jake",
  "roomname": "Jake's Room"
}
###
POST http://localhost:8080/room/member
Content-Type: application/json

{
  "username": "Jake21",
  "roomId": 1
}
###
POST http://localhost:8080/room/song
Content-Type: application/json

{
  "roomId": 1,
  "songId": 1
}
###
POST http://localhost:8080/room/song
Content-Type: application/json

{
  "roomId": 1,
  "song": {
    "title": "Never Gonna Give You Up",
    "artist": "Rick Astley",
    "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstleyVEV",
    "picUrl": "https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    "length": 212
  }
}
###

