GET http://localhost:8080/user/Jake
Content-Type: application/json
###
GET http://localhost:8080/user
Content-Type: application/json
###
GET http://localhost:8080/user/Jake/rooms
###
GET http://localhost:8080/user/Jake/members
###
GET http://localhost:8080/user/Jake/friends
###
GET http://localhost:8080/user/Jake21/friendRequests
###
GET http://localhost:8080/user/Jake21/friendRequests/1/true
###
GET http://localhost:8080/user/Jake21/roomInvites
###
GET http://localhost:8080/user/Jake21/roomInvites/1/true
###
POST http://localhost:8080/user
Content-Type: application/json

{
  "username": "Jake",
  "password": "passme",
  "displayname": "Jake",
  "picUrl": "http://..."

}
###
POST http://localhost:8080/user
Content-Type: application/json

{
  "username": "Jake21",
  "password": "passme",
  "displayname": "Jake",
  "picUrl": "http://..."

}
###
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "Jake",
  "password": "passme"
}
###
POST http://localhost:8080/user/update
Content-Type: application/json

{
  "username": "Jake",
  "changes": {
    "username": "Jake21",
    "displayname": "xX_Jake_Xx",
    "password": "password",
    "picUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstleyVEVO"
  }
}
###
POST http://localhost:8080/user/friend
Content-Type: application/json

{
  "username1": "Jake",
  "username2": "Jake22"
}
###
POST http://localhost:8080/user/friendRequest
Content-Type: application/json

{
  "sender": "Jake",
  "receiver": "Jake21"
}
###
POST http://localhost:8080/user/roomInvite
Content-Type: application/json

{
  "sender": "Jake",
  "receiver": "Jake21",
  "roomId": 1
}
###
DELETE http://localhost:8080/user/delete/Jake
Content-Type: application/json
###