GET http://localhost:8080/user/Jake
Content-Type: application/json
###
GET http://localhost:8080/user
Content-Type: application/json
###
GET http://localhost:8080/user/Jake/rooms
###
GET http://localhost:8080/user/Jake/members
###
POST http://localhost:8080/user
Content-Type: application/json

{
  "username": "Jake",
  "password": "passme",
  "displayname": "Jake",
  "picUrl": "http://..."

}
###
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "Jake",
  "password": "passme"
}
###
POST http://localhost:8080/user/update
Content-Type: application/json

{
  "username": "Jake",
  "changes": {
    "username": "Jake21",
    "displayname": "xX_Jake_Xx",
    "password": "password",
    "picUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstleyVEVO"
  }
}
###
DELETE http://localhost:8080/user/delete/Jake
Content-Type: application/json
###